# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

@Email=administrator@localhost
@Password=Administrator1!
@BearerToken=CfDJ8LtuR9E8bfNPknS7xBkRlQPL0zmc2KpahXI9pbkT40kLzSNG3_CdhXsYn7R-uZiCqHjgbZ6MJDMp97TtBtD_n0yurTpiMO4T1x1hoVcym-wGDQIP-HUpSunW-AtXC_LZw4aUljG_qwh5sz4HmsAlDJFL4iEuUCNxbQp_s07QTm_yqOym8vhNwlv41m6_nInybv-JnthxodQFoFmvNW80PTjTILDyQHJVZNCq03SfiK0bUak7Bjg79lxn5kyrXk4s7h3Pd_PcrlZzjsc_PgZjO0xWYRXZE6Q_8xlxbVkZInR-q3CB_WDRsJokj-9nsE9Y0Qeh1DR4tyRH9k75Lg1xW5eqsvKMVItbGmmwyM6tDhuf26sh7XX4pV6EhJuynCFuQofOtGZF_9r50A2vNAZmrnnCiAOPSqLLjElhDa8W2io0k2WuF-MlP03jR64YOWkFAneyZZOLK_YOM7xGHJIzfpN_Zi4WfrMlI6EMTKi9x8wlQqHD9cU-zE_um-O4BeJHzyl0_fF3bLkw-fJFCLnUgIBBVEVWrzMcL3A9r3_pzf9thbORPAZOodkeFAkO8iWJNWeC3LsuE6Gi_yyuRARvJ2wfEyaQ66UQFUTLwNC9zmXkhoAh5_E6TEo3c1Nxfw8ypYw1svVSRTDPp5ZcfuHLnOdweknj7zNwB69cAxNVYHUCR5XicIwg4tYV2SPe43saKBWLlacLR26G5sojhwH6HqwYNH3ZKSrWVKYOnFbpWcTsmysbussJtOgEaOCirFvAnLKEyDQTO6KfeUe1RjEW7zcnEK8ztb_exBR1wwRDfv9hiBVxEIV-rifvoq42ENQO1A

# POST Users Register
POST {{Web_HostAddress}}/api/Users/Register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Refresh
POST {{Web_HostAddress}}/api/Users/Refresh
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "refreshToken": ""
}

###

# GET WeatherForecast
GET {{Web_HostAddress}}/api/WeatherForecasts
Authorization: Bearer {{BearerToken}}

###

# GET TodoLists
GET {{Web_HostAddress}}/api/TodoLists
Authorization: Bearer {{BearerToken}}

###

# POST TodoLists
POST {{Web_HostAddress}}/api/TodoLists
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// CreateTodoListCommand
{
  "Title": "Backlog"
}

###

# PUT TodoLists
PUT {{Web_HostAddress}}/api/TodoLists/1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoListCommand
{
  "Id": 1,
  "Title": "Product Backlog"
}

###

# DELETE TodoLists
DELETE {{Web_HostAddress}}/api/TodoLists/1
Authorization: Bearer {{BearerToken}}

###

# GET TodoItems
@PageNumber = 1
@PageSize = 10
GET {{Web_HostAddress}}/api/TodoItems?ListId=1&PageNumber={{PageNumber}}&PageSize={{PageSize}}

Authorization: Bearer {{BearerToken}}

###

# POST TodoItems
POST {{Web_HostAddress}}/api/TodoItems
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// CreateTodoItemCommand
{
  "ListId": 1,
  "Title": "Eat a burrito 🌯"
}

###

#PUT TodoItems UpdateItemDetails
PUT {{Web_HostAddress}}/api/TodoItems/UpdateItemDetails?Id=1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoItemDetailCommand
{
  "Id": 1,
  "ListId": 1,
  "Priority": 3,
  "Note": "This is a good idea!"
}

###

# PUT TodoItems
PUT {{Web_HostAddress}}/api/TodoItems/1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoItemCommand
{
  "Id": 1,
  "Title": "Eat a yummy burrito 🌯",
  "Done": true
}

###

# DELETE TodoItem
DELETE {{Web_HostAddress}}/api/TodoItems/1
Authorization: Bearer {{BearerToken}}

###