# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

@Email=administrator@localhost
@Password=Administrator1!
@BearerToken=CfDJ8LtuR9E8bfNPknS7xBkRlQNDIwiQkZhfDgiHXU5xyp8tEbMeJhKHSdXrB1XYg4lVC8jNhbQoScMRgdv3obD-0z5AVcN75k7KkLU6uV4iPzSMy8cdlKcenlg4xc5ZgnzgkBi-OMmrBdfD8Xa1f4o8aEmsWgWLsJS7oGxaBbjzMP4dTS25xXflJ3ZXQI9617UISPwCkjknEVvYuIRoSBzIKd5Y7AzYNX6bojSK1lJ63YGRcJPnvqRgnp2Z1QkQk8yezQCjWN5obVOzlnt6qNGGdoXDPJhbpMX-_ziD6yvvw85tyZ33s2D5eHmDq9Ee4Qi3QDIBJdeI_Sni2MdOw49XD67gFEBe0YYZITIYMhIucg4Ab0wP5ww0z6EvR9kqmj41D-rYTYg_hBdnT8sgGXBODm2vtDwpMk_rlUMfc7eE8uhlsJRF8eONGlwmRtVvZvU61DFTIF8vXLlAbeAYPh5UDD08212yQtuO-tEyqRwmfm7Ax-Idpti-Ff1b6r_a_rdbvU6NoLZtCXBvhtKxHfbD2O7bR158KfEAE7N4mglsQo9k9IfgKGqos0yHCbdSVobEAHyn2Sv-MZ3XuqQU5-cWb7MYid30DjDYGOKFfWZiV6GcLe2IVSqASt3Gub_fYHuTCTAwFyswT_jwLyK3cfaMqfGAiQJtGvIfeclODTM-U4zQilFId5wp7ySG9vQTyjRb3f7LTP97MzekwfTK-IpURUy4N9_0XFqY2gAnSvRn04boieH4adLndxdHn7RAbX3u9Wwar7eJN6xzeoaargxcCdX-cfVtvWhb7WVPOjw-NpmrwGnGHXlfIRuG2WJnKElqtA
@RefreshToKen=CfDJ8LtuR9E8bfNPknS7xBkRlQNaCFcWOl3qujpTkJi0OWPCnI1Kr9IV8rqnkn3OWlpMEwsuMazMt7nXbXLvAO0v69JuRJHQRqFfpDadpCVugqK_8N-z183MpHtlaE57tDnDrQdgMoMYE-wusCyHsKyLAewYKunFSaMGdixDY9PtLFh_gbtKEN70QfBve1wpK9lIrh2DYl18Kb2EG65HavF997XReb6a34Di6NV4Ew1bnWLOolKoNzoBLLnoGycaJQL5Dis4u4AvTCb__HYyuZZik-5GN-qBqozngcKB7JdfmUp7zlP9vM_4juL8AaNKBKWPLlVTnVG8Z-6m-HVcpq43bLEcd-4FEmoFvxCZMaNw9tbIc6VlIP5R8v56x8dMXgQ3eNda7BPsVSMlpNnr7rI47zGR4GQwyoJs3rIBwcDS7QfvHBfQF_pvBT3siW16pIR_rAHc1ej9qv79z-5YS64QLMPzAK3Vgp9J7bLJcHdPhBAvYMpsQTP4ZWO-4B_I3d_xfEtx_HrFqGvKl2ouXWsTL6gr7gvYuiSKu8fs1G8sy79fmo0KhlOEjYLKdKykBM_cL7V-nsP55h2kc6k09Sd2r2GfivtqIxEo7hEqLEPaunUB093UjnMB8OWQuGw54Sh3rGBE10bYy7PtTKuOnHl2jHlFi3q9gFvIXEZw0lZDKw6eUMZVdnGloFip0JCv9JC4MdO8Rs-ZpyaEGdnVrX0j7gu2wBTFoneVGKuTudD922QEZDmtzFPYHwlnhicuQMcsY9s25LoTxCWChce6VTcFxGiG0RAJCQK-kWhUpwv7r1BLbBxj0DmhCBjJ19_qaZPDvS4LfE2bVO9KnF_WNrF_Bcg
# POST Users Register
POST {{Web_HostAddress}}/api/Users/Register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Refresh
POST {{Web_HostAddress}}/api/Users/Refresh
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "refreshToken": "{{RefreshToKen}}"
}

###

# GET WeatherForecast
GET {{Web_HostAddress}}/api/WeatherForecasts
Authorization: Bearer {{BearerToken}}

###

# GET TodoLists
GET {{Web_HostAddress}}/api/TodoLists
Authorization: Bearer {{BearerToken}}

###

# POST TodoLists
POST {{Web_HostAddress}}/api/TodoLists
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// CreateTodoListCommand
{
  "Title": "Backlog"
}

###

# PUT TodoLists
PUT {{Web_HostAddress}}/api/TodoLists/1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoListCommand
{
  "Id": 1,
  "Title": "Product Backlog"
}

###

# DELETE TodoLists
DELETE {{Web_HostAddress}}/api/TodoLists/1
Authorization: Bearer {{BearerToken}}

###

# GET TodoItems
@PageNumber = 1
@PageSize = 10
GET {{Web_HostAddress}}/api/TodoItems?ListId=1&PageNumber={{PageNumber}}&PageSize={{PageSize}}

Authorization: Bearer {{BearerToken}}

###

# POST TodoItems
POST {{Web_HostAddress}}/api/TodoItems
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// CreateTodoItemCommand
{
  "ListId": 1,
  "Title": "Eat a burrito 🌯"
}

###

#PUT TodoItems UpdateItemDetails
PUT {{Web_HostAddress}}/api/TodoItems/UpdateItemDetails?Id=1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoItemDetailCommand
{
  "Id": 1,
  "ListId": 1,
  "Priority": 3,
  "Note": "This is a good idea!"
}

###

# PUT TodoItems
PUT {{Web_HostAddress}}/api/TodoItems/1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoItemCommand
{
  "Id": 1,
  "Title": "Eat a yummy burrito 🌯",
  "Done": true
}

###

# DELETE TodoItem
DELETE {{Web_HostAddress}}/api/TodoItems/1
Authorization: Bearer {{BearerToken}}

###